AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  logsize: 100000
  log_generations: 3
#  app_dir: /conf/apps
  cert_verify: False
  disable_apps: 0 
  
HASS:
  # change to hassio's ip address in production
  ha_url: http://hass:8123 
HADashboard:
  # change to hassio's ip address without port in production
  dash_url: http://0.0.0.0:5050
  dash_dir: /conf/dashboards
  # dash_dir: /config/hadaemon/dashboards
  dash_force_compile: 1 
  dash_compile_on_start: 1