version: '3'
services:
  hass:
    image: homeassistant/home-assistant
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
    restart: always
  appdaemon:
    image: acockburn/appdaemon:latest
    depends_on: 
      - hass
    volumes:
      - ./config/hadaemon:/conf
    ports:
      - "5050:5050"