homeassistant:
  # Name of the location where Home Assistant is running
  name: Teamzoon
  # Location required to calculate the time the sun rises and sets
  latitude: 18.79970
  longitude: 99.02326
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 310
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Bangkok

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_port: 8123
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# MQTT
mqtt:
  broker: 139.59.120.107
  port : 1883
  client_id: "tz-home-assistant-2"

light left_lamp:
  - platform: mqtt
    name: "Left Lamp"
    state_topic: "tzswitch1/relay/state"
    command_topic: "tzswitch1/gpio/12"
    qos: 0
    payload_on: 1
    payload_off: 0
    retain: true
    optimistic: false

light right_lamp:
  - platform: mqtt
    name: "Right Lamp"
    state_topic: "tzswitch2/relay/state"
    command_topic: "tzswitch2/gpio/12"
    qos: 0
    payload_on: 1
    payload_off: 0
    retain: true
    optimistic: false

switch center_lamp:
  - platform: mqtt
    name: "Center Lamp"
    state_topic: "tzwifiswitch2/relay/state"
    command_topic: "tzwifiswitch2/gpio/12"
    qos: 0
    payload_on: 1
    payload_off: 0
    retain: true
    optimistic: false

# Text to speech
tts:
  - platform: google

automation: !include automations.yaml
